version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: infracciones_db
    ports:
      - "3000:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql